### ISSUE TITLE
deploy: migrate deployment tracking from cf-deployment-tracker-client to metrics-collector-service

### ISSUE THREAD

**Issue by aprilwebster** [watson-developer-cloud/customer-engagement-nodejs#14]
`cf-deployment-tracker-client` has been deprecated as of November 2017 (https://github.com/IBM-Cloud/cf-deployment-tracker-service/wiki/Deployment-Tracker-Service-status).  It is recommended to use the `metrics-collector-service` (https://github.com/IBM/metrics-collector-service) instead.

**Comment by germanattanasio** [comment]
@richieverma did you do this already?
